---
title: "assignment-b1"
output: github_document
---
# Getting Started
Load the libraries for this assignment: 
```{r, message = F}
library(tidyverse)
library(datateachr)
library(testthat)
```

# Exercise 1: Make a Function & Exercise 2: Document your Function
```{r}
# Make the function
count_NA <- function(data, col_name) {
  if(!is.character(col_name)) {
    stop("col_name needs to be a string")
  } else if (!(col_name %in% colnames(data))) {
    stop("'", col_name, "' does not exist in the data")
  } else {
    return(as_tibble(data %>% summarise(across(col_name, ~sum(is.na(.x))))))
  }
}

# Document the function
#' Count the missing values (NA) of a variable in a dataset
#'
#' @description `count_NA` returns the count of missing values (NA) in a specified column `col_name` of a given dataset `data`
#'
#' @param data Dataset to retrieve the specific column from
#' @param col_name Name of the column (string input) to count missing value(s)
#'
#' @return A tibble (of the dimensions 1 x 1) with variable "col_name" and its value of the integer count of missing values (NA) 
```

# Exercise 3: Include examples
Examples using the "cancer_sample" dataset from the package "datateachr"
```{r}
# Count the missing values of the "diagnosis" and "radius_mean" variables in the "cancer_sample" dataset
count_NA(cancer_sample, "diagnosis")
count_NA(cancer_sample, "radius_mean")
```

```{r, error = TRUE}
# A failed example, as the input is not a string
# The error message of "col_name needs to be a string" will appear
count_NA(cancer_sample, 123)

# A failed example, as the input is not a column in the "cancer_sample" dataset
# The error message of "'diagnosis_year' does not exist in the data" will appear
count_NA(cancer_sample, "diagnosis_year")
```

# Exercise 4: Test the Function
```{r}
# Three expect statements are used to test the function
test_that("Test the function 'count_NA' with dataset 'cancer_sample'", {
  expect_equal(count_NA(cancer_sample, "diagnosis"), as_tibble(summarise(cancer_sample, across(diagnosis, ~ sum(is.na(.x))))))
  expect_equal(count_NA(cancer_sample, "radius_mean"), as_tibble(summarise(cancer_sample, across(radius_mean, ~ sum(is.na(.x))))))
  expect_error(count_NA(cancer_sample, 123), "col_name needs to be a string")
  expect_error(count_NA(cancer_sample, "diagnosis_year"), "'diagnosis_year' does not exist in the data")
  expect_true(is_tibble(count_NA(cancer_sample, "diagnosis")))
})
```
